use_frameworks!

platform :ios, '8.0'

target 'UIViewController-JXPagingView_Example' do
  pod 'UIViewController-JXPagingView', :path => '../'

  target 'UIViewController-JXPagingView_Tests' do
    inherit! :search_paths

    
  end
end
